// ── Language switcher — full DOM direction + text swap ──────────────────────
function applyLang(lang) {
  const html = document.documentElement;
  html.setAttribute('lang', lang);
  html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

  // Font swap
  document.body.style.fontFamily = lang === 'ar'
    ? "'Almarai', system-ui, sans-serif"
    : "'Inter', system-ui, sans-serif";

  // Translate all [data-i18n] elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = TRANSLATIONS[lang]?.[key];
    if (val !== undefined) el.textContent = val;
  });

  // Translate placeholders
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    const val = TRANSLATIONS[lang]?.[key];
    if (val !== undefined) el.placeholder = val;
  });

  // Replace static text-right/text-left with text-start/text-end
  document.querySelectorAll('.text-right').forEach(el => {
    el.classList.remove('text-right'); el.classList.add('text-start');
  });
  document.querySelectorAll('.text-left').forEach(el => {
    el.classList.remove('text-left'); el.classList.add('text-end');
  });

  // Flip sidebar position for LTR
  const sidebar = document.querySelector('.sidebar');
  if (sidebar) {
    if (lang === 'en') {
      sidebar.style.right = 'auto';
      sidebar.style.left = '0';
      sidebar.style.borderLeft = 'none';
      sidebar.style.borderRight = '1px solid var(--line)';
    } else {
      sidebar.style.right = '0';
      sidebar.style.left = 'auto';
      sidebar.style.borderRight = 'none';
      sidebar.style.borderLeft = '1px solid var(--line)';
    }
  }

  // Update lang button text
  document.querySelectorAll('.lang-btn, .lang-toggle, [data-lang-btn]').forEach(btn => {
    btn.textContent = lang === 'ar' ? 'EN' : 'عربي';
  });

  // Persist
  localStorage.setItem('vm_lang', lang);
}

function toggleLang() {
  const current = localStorage.getItem('vm_lang') || 'ar';
  applyLang(current === 'ar' ? 'en' : 'ar');
}

// Auto-apply on load
document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('vm_lang') || 'ar';
  applyLang(saved);
});

// ── VOLD MOTOR — Bilingual i18n System ────────────────────────────────────────
const TRANSLATIONS = {
  ar: {

    /* ── ADMIN (auto) ── */
    'stat.total': 'إجمالي الطلبات',
    'stat.pending': 'طلبات معلّقة',
    'stat.approved': 'مراكز مفعّلة',
    'stat.rejected': 'طلبات مرفوضة',
    'ad.overview': 'نظرة عامة',
    'ad.joinRequests': 'طلبات الانضمام',
    'ad.platform': 'المنصة',
    'ad.subscribedCenters': 'المراكز المشتركة',
    'ad.platformStats': 'إحصائيات المنصة',
    'ad.rejectedRequests': 'الطلبات المرفوضة',
    'ad.title': 'لوحة الإدارة العليا',
    'ad.refresh': 'تحديث',
    'ad.platformRevenue': 'إجمالي دخل المنصة · هذا الشهر',
    'ad.underDev': 'قيد التطوير — سيُعرض قريباً',
    'ad.refreshNow': 'تحديث الآن',
    'ad.viewReport': 'عرض التقرير',
    'ad.sinceLaunch': 'منذ الإطلاق',
    'ad.needReview': '⚠ تحتاج مراجعة',
    'ad.careCenter': 'مراكز عناية',
    'ad.mechShop': 'ورش ميكانيكا',
    'ad.tintCenter': 'مراكز تظليل',
    'ad.ofTotal': 'من إجمالي الطلبات',
    'ad.monthlyGrowth': 'نمو الانضمامات الشهري',
    'ad.monthlyGrowthSub': 'عدد طلبات الانضمام الجديدة لهذا العام',
    'ad.monthly': 'شهري',
    'ad.yearly': 'سنوي',
    'ad.statusDist': 'توزيع حالات الطلبات',
    'ad.statusDistSub': 'نسبة القبول والرفض والانتظار',
    'ad.statApproved': 'مفعّل',
    'ad.statPending': 'انتظار',
    'ad.statRejected': 'مرفوض',
    'ad.allRequests': 'جميع الطلبات',
    'ad.fPending': 'معلّق',
    'ad.searchPh': 'بحث...',
    'ad.rejectTitle': 'رفض الطلب',
    'ad.rejectDesc': 'يمكنك إضافة ملاحظة للمتقدم (اختياري)',
    'ad.rejectPh': 'سبب الرفض أو ملاحظات...',
    'ad.rejectBtn': 'رفض الطلب',

    /* ── SETTINGS (auto) ── */
    's.center': 'المركز',
    's.svcPricesMenu': 'الخدمات والأسعار',
    's.account': 'الحساب',
    's.notifications': 'الإشعارات',
    's.danger': 'منطقة الخطر',
    's.centerInfo': 'معلومات المركز',
    's.centerDesc': 'البيانات الأساسية التي تظهر في الفواتير والتقارير',
    's.centerName': 'اسم المركز',
    's.centerNamePh': 'مثال: VOLD MOTOR',
    's.city': 'المدينة',
    's.cityPh': 'الرياض',
    's.district': 'الحي',
    's.districtPh': 'حي النسيم',
    's.address': 'عنوان المركز (اختياري)',
    's.addressPh': 'شارع الملك فهد، حي النسيم',
    's.openTime': 'وقت الفتح',
    's.closeTime': 'وقت الإغلاق',
    's.invoiceNote': 'ملاحظة تظهر في الفاتورة (اختياري)',
    's.invoiceNotePh': 'شكراً لزيارتكم...',
    's.svcPrices': 'أسعار الخدمات',
    's.svcPricesDesc': 'حدد السعر الافتراضي لكل خدمة — يمكن تعديله عند كل عملية في الكاشير',
    's.savePrices': 'حفظ الأسعار',
    's.accInfo': 'بيانات الحساب',
    's.accDesc': 'معلومات حساب المركز',
    's.emailOrPhone': 'البريد الإلكتروني / رقم الجوال',
    's.newPw': 'كلمة مرور جديدة',
    's.newPwPh': 'اتركه فارغاً إذا لا تريد تغييره',
    's.confirmPw': 'تأكيد كلمة المرور',
    's.confirmPwPh': 'أعد كتابة كلمة المرور',
    's.updatePw': 'تحديث كلمة المرور',
    's.notifSettings': 'إعدادات الإشعارات',
    's.notifDesc': 'تحكم في التنبيهات التي تصلك',
    's.notifVisit': 'تنبيه عند إضافة عملية جديدة',
    's.notifVisitSub': 'صوت تنبيه عند حفظ زيارة في الكاشير',
    's.notifPromo': 'تنبيه انتهاء أكواد الخصم',
    's.notifPromoSub': 'تنبيه عند اقتراب انتهاء صلاحية كود الخصم',
    's.notifDaily': 'تقرير يومي',
    's.notifDailySub': 'ملخص إيرادات اليوم عند نهاية الدوام',
    's.notifNewCust': 'تنبيه العميل الجديد',
    's.notifNewCustSub': 'تنبيه عند تسجيل سيارة لأول مرة',
    's.saveSettings': 'حفظ الإعدادات',
    's.dangerTitle': '⚠️ منطقة الخطر',
    's.dangerDesc': 'هذه الإجراءات لا يمكن التراجع عنها',
    's.delMonth': 'مسح بيانات الشهر',
    's.delMonthSub': 'حذف جميع زيارات ومصروفات الشهر الحالي',
    's.delete': 'مسح',
    's.delAll': 'مسح كل البيانات',
    's.delAllSub': 'حذف جميع الزيارات والمصروفات وأكواد الخصم',
    's.deleteAll': 'مسح الكل',
    's.logout': 'تسجيل الخروج',
    's.logoutSub': 'الخروج من الحساب على هذا الجهاز',
    's.logoutBtn': 'خروج',
    's.savedOk': '✅ تم الحفظ بنجاح',

    /* ── TEAM (auto) ── */
    't.addEmp': 'إضافة موظف',
    't.totalTeam': 'إجمالي الفريق',
    't.employee': 'موظف',
    't.managers': 'المديرون',
    't.manager': 'مدير',
    't.cashiers': 'الكاشيرون',
    't.cashier': 'كاشير',
    't.techs': 'الفنيون',
    't.tech': 'فني',
    't.noEmp': 'لا يوجد موظفون بعد',
    't.noEmpSub': 'ابدأ بإضافة أول موظف في فريقك',
    't.addEmpTitle': 'إضافة موظف جديد',
    't.nameReq': 'الاسم *',
    't.namePh': 'محمد أحمد',
    't.roleReq': 'الدور *',
    't.chooseRole': 'اختر الدور...',
    't.cleaning': 'عامل نظافة',
    't.salary': 'الراتب (ر.س)',
    't.hireDate': 'تاريخ التوظيف',
    't.active': 'نشط',
    't.leave': 'إجازة',
    't.inactive': 'غير نشط',
    't.notesPh': 'أي ملاحظات إضافية...',
    't.save': 'حفظ',
    't.saved': '✅ تم الحفظ',

    /* ── REPORTS (auto) ── */
    'r.exportCsv': 'تصدير CSV',
    'r.print': 'طباعة',
    'r.thisYear': 'هذه السنة',
    'r.custom': 'مخصص',
    'r.from': 'من:',
    'r.to': 'إلى:',
    'r.apply': 'تطبيق',
    'r.totalRev': 'إجمالي الإيرادات',
    'r.totalExp': 'إجمالي المصروفات',
    'r.carCount': 'عدد السيارات',
    'r.visit': 'زيارة',
    'r.revVsExp': 'الإيرادات والمصروفات',
    'r.svcDist': 'توزيع الخدمات',
    'r.mostReq': 'الأكثر طلباً',
    'r.svcRank': 'ترتيب الخدمات',
    'r.byOrders': 'حسب عدد الطلبات',
    'r.lastVisits': 'آخر الزيارات',
    'r.expDist': 'توزيع المصروفات',
    'r.byCategory': 'حسب الفئة',
    'r.lastExp': 'آخر المصروفات',
    'r.thPlate': 'اللوحة',
    'r.thService': 'الخدمة',
    'r.thNet': 'الصافي',
    'r.thAmount': 'المبلغ',
    'r.loading': 'جاري التحميل...',

    /* ── EXPENSES (auto) ── */
    'e.title': '💰 المصروفات',
    'e.monthExp': 'مصروفات الشهر',
    'e.todayExp': 'مصروفات اليوم',
    'e.topItem': 'أكبر بند',
    'e.itemCount': 'عدد البنود هذا الشهر',
    'e.addExp': '➕ إضافة مصروف',
    'e.catRent': '🏠 إيجار',
    'e.catElec': '⚡ كهرباء',
    'e.catWater': '💧 مياه',
    'e.catSalary': '👷 رواتب',
    'e.catSupplies': '🛒 مستلزمات',
    'e.catOther': '📦 أخرى',
    'e.desc': 'الوصف',
    'e.descPh': 'مثال: إيجار شهر يناير',
    'e.amount': 'المبلغ (ريال)',
    'e.recurring': 'مصروف دوري (شهري)',
    'e.save': 'حفظ المصروف',
    'e.log': 'سجل المصروفات',

    /* ── MESSAGES (auto) ── */
    'm.templates': 'القوالب',
    'm.newMsg': 'رسالة جديدة',
    'm.searchConv': 'ابحث في المحادثات...',
    'm.unread': 'غير مقروء',
    'm.sent': 'مُرسلة',
    'm.chooseConv': 'اختر محادثة',
    'm.chooseConvSub': 'اختر محادثة من القائمة أو ابدأ رسالة جديدة',
    'm.waInputPh': 'اكتب رسالة واتساب...',
    'm.templatesTitle': 'قوالب الرسائل',
    'm.message': 'الرسالة',
    'm.msgPh': 'اكتب رسالتك هنا...',
    'm.orTemplate': 'أو اختر قالباً:',
    'm.custSearchPh': 'ابحث باسم العميل أو الجوال...',
    'm.sendWa': 'إرسال واتساب',

    /* ── INVENTORY (auto) ── */
    'i.logMovement': 'تسجيل حركة',
    'i.newItem': 'صنف جديد',
    'i.totalItems': 'إجمالي الأصناف',
    'i.thisMonth': 'هذا الشهر',
    'i.invValue': 'قيمة المخزون',
    'i.lowStock': 'أصناف منخفضة',
    'i.needReorder': 'تحتاج إعادة طلب',
    'i.outStock': 'نفد من المخزون',
    'i.orderNow': 'يجب الطلب فوراً',
    'i.alertReorder': 'تنبيه: 6 أصناف تحتاج إعادة طلب',
    'i.catOil': 'زيوت',
    'i.catFilter': 'فلاتر',
    'i.catTire': 'إطارات',
    'i.catBrake': 'فرامل',
    'i.catSpark': 'شمعات',
    'i.catOther': 'أخرى',
    'i.searchPh': 'ابحث باسم الصنف أو الرقم المرجعي...',
    'i.thItem': 'الصنف',
    'i.thCat': 'الفئة',
    'i.thQty': 'الكمية',
    'i.thMin': 'الحد الأدنى',
    'i.thStock': 'المخزون',
    'i.thUnitPrice': 'سعر الوحدة',
    'i.thTotal': 'الإجمالي',
    'i.addTitle': 'إضافة صنف جديد',
    'i.itemName': 'اسم الصنف',
    'i.itemNamePh': 'مثال: زيت موتور 5W-30',
    'i.category': 'الفئة',
    'i.curQty': 'الكمية الحالية',
    'i.minAlert': 'الحد الأدنى للتنبيه',
    'i.unitPriceSar': 'سعر الوحدة (ر.س)',
    'i.sku': 'الرقم المرجعي',
    'i.supplierPh': 'مورّد، تفاصيل إضافية...',
    'i.saveItem': 'حفظ الصنف',
    'i.moveTitle': 'تسجيل حركة مخزون',
    'i.moveType': 'نوع الحركة',
    'i.addStock': 'إضافة للمخزون',
    'i.removeStock': 'سحب من المخزون',
    'i.item': 'الصنف',
    'i.chooseItem': 'اختر الصنف...',
    'i.reason': 'السبب / الملاحظة',
    'i.reasonPh': 'مثال: استخدام في حجز #124، استلام من المورّد...',
    'i.lastMoves': 'آخر الحركات',
    'i.saveMove': 'تسجيل الحركة',
    'i.totalValue': 'إجمالي القيمة',
    'i.logMovementShort': '+ تسجيل حركة',
    'i.close': 'إغلاق',

    /* ── POS (auto) ── */
    'p.title': '🖥️ الكاشير',
    'p.plate': '🚗 رقم اللوحة',
    'p.platePh': 'أدخل رقم اللوحة',
    'p.phone': '📱 رقم الجوال',
    'p.custName': '👤 اسم العميل',
    'p.optional': '(اختياري)',
    'p.svcType': '🔧 نوع الخدمة',
    'p.svcTire': 'بنشري',
    'p.svcBattery': 'تبديل بطارية',
    'p.svcLube': 'تشحيم',
    'p.price': '💰 السعر (ريال)',
    'p.promo': '🏷️ كود الخصم',
    'p.notes': '📝 ملاحظات',
    'p.saveVisit': 'حفظ الزيارة وإصدار الفاتورة',
    'p.todayLog': 'سجل اليوم',
    'p.noVisits': 'لا توجد زيارات اليوم بعد',
    'p.enterData': 'أدخل بيانات الزيارة لمعاينة الفاتورة',
    'p.printInvoice': 'طباعة الفاتورة',
    'p.visitDone': 'تمت الزيارة ✅',
    'p.creditAdded': '🎁 تم إضافة رصيد للزيارة القادمة',
    'p.firstPromo': '🏷️ كود الخصم الأول',
    'p.valid30once': 'صالح 30 يوماً · مرة واحدة فقط',
    'p.newVisit': 'زيارة جديدة',
    'p.print': '🖨️ طباعة',

    /* ── APPOINTMENTS (auto) ── */
    'a.viewList': 'قائمة',
    'a.viewDay': 'اليوم',
    'a.viewWeek': 'الأسبوع',
    'a.newBooking': 'حجز جديد',
    'a.vsYesterday': 'عن أمس',
    'a.inProgress': 'قيد التنفيذ',
    'a.nowAtCenter': 'الآن في المركز',
    'a.completedToday': 'مكتملة اليوم',
    'a.completion': 'إنجاز',
    'a.sar': 'ريال سعودي',
    'a.fAll': 'الكل',
    'a.fPending': 'بانتظار',
    'a.fProgress': 'جارٍ',
    'a.fCancel': 'ملغي',
    'a.plateReq': 'رقم اللوحة *',
    'a.platePh': 'ABC 1234',
    'a.custOpt': 'اسم العميل (اختياري)',
    'a.serviceReq': 'الخدمة *',
    'a.chooseService': 'اختر الخدمة...',
    'a.svcPolish': 'تلميع',
    'a.svcTire': 'بناشر',
    'a.date': 'التاريخ',
    'a.time': 'الوقت',
    'a.duration': 'المدة المتوقعة',
    'a.dur30': '30 دقيقة',
    'a.dur60': 'ساعة',
    'a.dur90': 'ساعة ونص',
    'a.dur120': 'ساعتان',
    'a.dur180': '3 ساعات',
    'a.expectedCost': 'التكلفة المتوقعة (ر.س)',
    'a.notesPh': 'أي تفاصيل إضافية...',
    'a.saveBooking': 'حفظ الحجز',

    /* ── CUSTOMERS (auto) ── */
    'c.back': 'العودة',
    'c.newCust': 'عميل جديد',
    'c.totalCust': 'إجمالي العملاء',
    'c.custMonth': 'عملاء هذا الشهر',
    'c.carsReg': 'سيارات مسجّلة',
    'c.thisWeek': 'هذا الأسبوع',
    'c.vsLastMonth': 'عن الشهر الماضي',
    'c.avgCars': 'متوسط 1.6 سيارة/عميل',
    'c.searchPh': 'ابحث بالاسم أو رقم الجوال أو رقم اللوحة...',
    'c.filter': 'فلتر',
    'c.sort': 'ترتيب',
    'c.loading': 'جاري تحميل العملاء...',
    'c.addTitle': 'إضافة عميل جديد',
    'c.custNamePh': 'اسم العميل',
    'c.carData': 'بيانات السيارة',
    'c.platePh': 'أ ب ج 1234',
    'c.carPh': 'كامري، باترول...',
    'c.notes': 'ملاحظات',
    'c.notesPh': 'أي ملاحظات...',
    'c.cancel': 'إلغاء',
    'c.saveCust': 'حفظ العميل',
    'c.mobile': 'الجوال',
    'c.totalVisits': 'إجمالي الزيارات',
    'c.totalSpend': 'إجمالي الإنفاق',
    'c.whatsapp': 'راسل عبر واتساب',
    'c.newBooking': '+ حجز جديد',
    'c.editData': 'تعديل البيانات',

    /* ── DASHBOARD (auto) ── */
    'stat.todayRev': 'دخل اليوم',
    'stat.todayCars': 'سيارات اليوم',
    'stat.customers': 'العملاء',
    'stat.monthRev': 'دخل الشهر',
    'stat.netProfit': 'صافي الربح',
    'd.nav.dash': 'لوحة التحكم',
    'd.nav.pos': 'الكاشير',
    'd.nav.appt': 'الحجوزات',
    'd.nav.cust': 'العملاء',
    'd.nav.inv': 'المخزون',
    'd.sec.comm': 'التواصل',
    'd.nav.msg': 'الرسائل',
    'd.nav.exp': 'المصروفات',
    'd.nav.rep': 'التقارير',
    'd.nav.team': 'الفريق',
    'd.nav.set': 'الإعدادات',
    'd.home': 'الرئيسية',
    'd.pageTitle': 'لوحة التحكم',
    'd.newTx': 'عملية جديدة',
    'd.lastHour': '⚡ أداء آخر ساعة',
    'd.q.appt': 'حجوزات',
    'd.q.exp': 'مصروفات',
    'd.lastHourMini': 'أداء آخر ساعة',
    'd.vsDaily': 'مقارنة بالمتوسط اليومي',
    'd.carsLastHour': 'سيارة دخلت آخر ساعة',
    'd.techOcc': 'إشغال الفنيين',
    'd.realWork': 'نسبة العمل الفعلي اليوم',
    'd.teamCapacity': 'من طاقة الفريق الكاملة',
    'd.todayBookings': 'حجوزات اليوم',
    'd.upcomingInprog': 'قادم + جاري العمل',
    'd.activeNow': 'حجز نشط الآن',
    'd.upcoming': 'قادم',
    'd.inprog': 'جاري',
    'd.dailyIncome': '📈 الدخل اليومي — هذا الشهر',
    'd.fromPos': 'من الكاشير',
    'd.expensesBtn': '💰 المصروفات',
    'd.peakHours': '⏰ أوقات الذروة — هذا الأسبوع',
    'd.peakSub': 'أكثر ساعات الإقبال على مدار أيام الأسبوع',
    'd.thisWeek': 'هذا الأسبوع',
    'd.dailyCars': 'سيارات يومية',
    'd.peakDays': 'أيام الذروة',
    'd.viewAll': 'عرض الكل',
    'd.recentActivity': 'آخر النشاطات',
    'd.topServices': 'أكثر الخدمات طلباً',
    'd.thisMonth': 'هذا الشهر',
    'd.newTxH': 'عملية جديدة',
    'd.newTxSub': 'سجّل خدمة جديدة للمركز',
    'd.customer': 'العميل',
    'd.searchCust': 'ابحث باسم أو رقم الجوال...',
    'd.newCust': 'عميل جديد',
    'd.fullName': 'الاسم الكامل',
    'd.phone': 'رقم الجوال',
    'd.svcType': 'نوع الخدمة',
    'd.svc.wash': 'غسيل',
    'd.svc.tint': 'تظليل',
    'd.svc.maint': 'صيانة',
    'd.svc.oil': 'تغيير زيت',
    'd.svc.detail': 'تزيين',
    'd.svc.paint': 'حماية طلاء',
    'd.carType': 'نوع السيارة',
    'd.carPh': 'كامري / هايلوكس...',
    'd.plate': 'رقم اللوحة',
    'd.amount': 'المبلغ (ر.س)',
    'd.status': 'الحالة',
    'd.st.pending': 'قادم',
    'd.st.inprog': 'جاري',
    'd.st.done': 'مكتمل',
    'd.paid': 'تم استلام الدفع',
    'd.saveTx': 'حفظ العملية',
    // ── NAV (index) ──
    'nav.features':       'المزايا',
    'nav.results':        'النتائج',
    'nav.pricing':        'الأسعار',
    'nav.testimonials':   'آراء العملاء',
    'nav.login':          'تسجيل الدخول',
    'nav.register':       'سجّل مركزك مجاناً',

    // ── HERO ──
    'hero.pill':          'نظام إدارة مراكز العناية بالمركبات',
    'hero.h1.a':          'المنصة الأولى لإدارة',
    'hero.h1.b':          'مراكز العناية بالمركبات',
    'hero.h1.c':          '',
    'hero.badge':         'صُنع في السعودية 🇸🇦 لمراكز العناية بالمركبات',
    'hero.fc1':           'دخل اليوم',
    'hero.fc2':           'حجز اليوم',
    'hero.lead':          'سواء كان نشاطك مغسلة، تلميع، أو غيار زيوت؛ صممنا هذا النظام ليتشكل على مقاسك. تتبع كل سيارة من دخولها حتى خروجها، وابقَ على تواصل مع عملائك بضغطة زر.',
    'hero.cta1':          'سجّل مركزك مجاناً',
    'hero.cta2':          'استكشف المزايا',
    'hero.tag':           'نظام سحابي لإدارة مراكز العناية بالمركبات',
    'hero.note':          'بدون اشتراك شهري · عمولة رمزية على العمليات المكتملة فقط',
    'hero.rating':        'تقييم 4.9/5 من أصحاب المراكز',
    'hero.partners':      '+400 مركز شريك يثق بنا',
    'hero.stat1.val':     '4٬250 ر.س',
    'hero.stat1.lbl':     'دخل اليوم',
    'hero.stat2.val':     '18 حجز',
    'hero.stat2.lbl':     'اليوم',

    // ── TRUST ──
    'trust.1.lbl':  'مركز شريك',
    'trust.2.lbl':  'عملية مُدارة شهرياً',
    'trust.3.lbl':  'تقييم أصحاب المراكز',
    'trust.4.lbl':  'جاهزية النظام',

    // ── FEATURES ──
    'feat.eyebrow':   'المزايا',
    'feat.h2':        'نظام واحد يدير مركزك بالكامل',
    'feat.sub':       'ودّع الدفاتر الورقية وجداول الإكسل — كل شيء في مكان واحد منظّم.',
    'feat.1.title':   'إدارة الحجوزات',
    'feat.1.desc':'تقويم يومي وأسبوعي واضح لنشاطك أنت — كل حساب مستقل يعرض خدمات مجاله فقط، بدون خلط مع أنشطة ثانية.',
    'feat.2.title':   'قاعدة بيانات العملاء',
    'feat.2.desc':    'سجل كامل لكل عميل وسياراته — ابحث بالاسم أو رقم اللوحة في ثانية.',
    'feat.3.title':   'إدارة المخزون',
    'feat.3.desc':    'تتبّع زيوت وإطارات وقطع الغيار — تنبيه تلقائي عند انخفاض الكميات.',
    'feat.4.title':   'تواصل واتساب',
    'feat.4.desc':    'أرسل تذكيرات وتأكيدات وعروض لعملائك عبر واتساب مباشرة من النظام.',
    'feat.5.title':   'تقارير الدخل',
    'feat.5.desc':    'دخل يومي وشهري وسنوي — قرارات أوضح ببيانات حقيقية من مركزك.',
    'feat.6.title':'تابع عمالك وأنت في بيتك',
    'feat.6.desc':'حساب للمشرف بلوحة كاملة، وحسابات للعمالة للإدخال فقط — العامل يحدّث حالة كل سيارة بثلاث مراحل، وأنت تشوف السرعة والإنجاز من جوالك أينما كنت.',

    // ── SPLIT 1 ──
    'split1.eyebrow': 'تواصل واتساب',
    'split1.h3':      'تواصل مع عملائك مباشرة من النظام',
    'split1.p':       'أرسل تذكيرات المواعيد وتأكيدات العمليات والعروض الخاصة — كل شي من VOLD MOTOR بدون تطبيق منفصل.',
    'split1.li1':     'تذكير تلقائي قبل الموعد',
    'split1.li2':     'تأكيد العملية بعد الانتهاء',
    'split1.li3':     'إرسال عروض وخصومات للعملاء',
    'split1.li4':     'تذكير بموعد الصيانة الدورية',

    // ── SPLIT 2 ──
    'split2.eyebrow': 'المخزون',
    'split2.h3':      'تحكّم في مخزونك بدقة',
    'split2.p':       'سجّل كل منتج وكميته وسعره — وتلقّ تنبيهاً تلقائياً لما ينخفض المخزون عن الحد الأدنى.',
    'split2.li1':     'زيوت وإطارات وقطع غيار',
    'split2.li2':     'تنبيه عند نقص الكميات',
    'split2.li3':     'ربط المخزون بالعمليات اليومية',

    // ── RESULTS ──
    'res.eyebrow':  'النتائج',
    'res.h2':       'كونوا أنتم مدراء أعمالكم',
    'res.sub':      'VOLD MOTOR يساعدك على تنمية مركزك وزيادة دخلك.',
    'res.1.title':  'زيادة في العملاء',
    'res.1.desc':   'وصّل خدماتك لعملاء جدد وشجّعهم على العودة.',
    'res.2.title':  'التزام بالمواعيد',
    'res.2.desc':   'قلّل التأخّر والغياب عبر تذكيرات واتساب التلقائية.',
    'res.3.title':  'زيادة في الدخل',
    'res.3.desc':   'نظّم طابورك وأضف خدمات إضافية وقت الزيارة.',

    // ── TESTIMONIALS ──
    'tst.eyebrow':  'آراء العملاء',
    'tst.h2':       'أصحاب مراكز مثلك يثقون بـ VOLD MOTOR',
    'tst.1.q':      'قبل VOLD MOTOR كنت أكتب كل شي في دفتر. الحين المخزون والحجوزات والعملاء كلهم بمكان واحد.',
    'tst.1.name':   'أبو فيصل',
    'tst.1.sub':    'مركز اللمسة الذهبية · الدمام',
    'tst.2.q':      'التذكير بواتساب غيّر حياتي — العملاء ما ينسون مواعيدهم وصار عندي وقت فاضي أستقبل زبائن جدد.',
    'tst.2.name':   'محمد القحطاني',
    'tst.2.sub':    'مركز برو كير · الخبر',
    'tst.3.q':      'التقارير الشهرية وضّحت لي إن خدمة التظليل هي الأعلى دخلاً — غيّرت تركيزي وزاد ربحي.',
    'tst.3.name':   'سعد العتيبي',
    'tst.3.sub':    'مركز إتقان · الرياض',

    // ── PRICING — Commission Model ──
    'price.eyebrow':      'العمولة',
    'price.h2':           'ادفع فقط لما تكسب',
    'price.sub':          'بدون اشتراك شهري. عمولة رمزية على العمليات المكتملة فقط — مصلحتنا مرتبطة بنجاحك.',
    'price.badge':        'بدون اشتراك شهري',
    'price.name':         'نموذج العمولة',
            'price.tier1.amount': '2.5',
            'price.tier2.amount': '6.5',
        'price.li1':          'لا رسوم شهرية ثابتة',
    'price.li2':          'بعقود واضحة تحفظ حقوق الطرفين',
    'price.li3':          'يُحسب فقط على العمليات المكتملة',
    'price.li4':          'جميع المزايا مفتوحة بلا حدود',
    'price.cta':          'سجّل مركزك مجاناً',

    // ── CTA ──
    'cta.h2':   'مركزك يستاهل نظام أفضل',
    'cta.p':    'انضم لأكثر من 400 مركز نظّم شغله مع VOLD MOTOR. ابدأ اليوم — مجاناً.',
    'cta.btn1': 'سجّل مركزك الآن',
    'cta.btn2': 'اعرف أكثر',

    // ── FOOTER ──
    'foot.desc':      'نظام إدارة مراكز العناية بالمركبات — صُمّم في السعودية.',
    'foot.col1.h':    'المنتج',
    'foot.col1.l1':   'المزايا',
    'foot.col1.l2':   'الأسعار',
    'foot.col1.l3':   'النتائج',
    'foot.col2.h':    'الشركة',
    'foot.col2.l1':   'من نحن',
    'foot.col2.l2':   'تواصل معنا',
    'foot.col2.l3':   'الأسئلة الشائعة',
    'foot.col3.h':    'الدعم',
    'foot.col3.l1':   'مركز المساعدة',
    'foot.col3.l2':   'الأسئلة الشائعة',
    'foot.col3.l3':   'سياسة الخصوصية',
    'foot.copy':      '© 2026 VOLD MOTOR · جميع الحقوق محفوظة',

    // ── LOGIN ──
    'login.s1.title':       'إنشاء حساب جديد / تسجيل الدخول',
    'login.merchant.h':     'صاحب مركز',
    'login.merchant.sub':   'أدِر حجوزاتك وعملاءك ومخزونك',
    'login.admin.h':        'إدارة النظام',
    'login.admin.sub':      'لوحة تحكم الأدمن والإشراف على المراكز',
    'login.back':           'رجوع',
    'login.help':           'المساعدة',
    'login.privacy':        'سياسة الخصوصية',
    'login.terms':          'الشروط',
    // S2 picker
    'login.picker.title':   'صاحب مركز؟',
    'login.picker.sub':     'اختر ما يناسبك',
    'login.reg.badge':      'بدون اشتراكات شهرية',
    'login.reg.title':      'سجّل مركزك الآن',
    'login.reg.sub':        'ابدأ في دقائق — التسجيل مجاني',
    'login.reg.perk1':      'إدارة الحجوزات والعملاء',
    'login.reg.perk2':      'تقارير الدخل والمخزون',
    'login.reg.perk3':      'إلغاء في أي وقت',
    'login.reg.cta':        'ابدأ الآن',
    'login.or':             'أو',
    'login.haveacc.h':      'عندي حساب',
    'login.haveacc.sub':    'سجّل دخولك للنظام',
    // tl2
    'login.signin.title':   'تسجيل الدخول',
    'login.signin.sub':     'أدخل بيانات حسابك',
    'login.phone.lbl':      'رقم الجوال',
    'login.pass.lbl':       'كلمة المرور',
    'login.forgot':         'نسيت كلمة المرور؟',
    'login.btn.login':      'دخول للنظام',
    'login.sw.noreg':       'ليس لديك حساب؟',
    'login.sw.reg':         'سجّل مركزك مجاناً',
    // tr2
    'login.reg.hdr.title':  'تسجيل مركز جديد',
    'login.reg.hdr.sub':    'بدون اشتراكات شهرية · عمولة على الطلبات المنجزة فقط',
    'login.shop.lbl':       'اسم المركز',
    'login.ntype.lbl':      'نوع النشاط',
    'login.ntype.wash':     'غسيل',
    'login.ntype.tint':     'تظليل',
    'login.ntype.maint':    'صيانة',
    'login.ntype.oil':      'تغيير زيت',
    'login.ntype.detail':   'تزيين',
    'login.ntype.ppf':      'حماية طلاء',
    'login.name.lbl':       'الاسم الكامل',
    'login.btn.reg':        'إنشاء حساب المركز',
    'login.sw.haveacc':     'عندك حساب؟',
    'login.sw.dologin':     'سجّل الدخول',
    // s3
    'login.s3.title':       'لوحة الإدارة',
    'login.s3.sub':         'الدخول خاص بإدارة النظام',
    'login.email.lbl':      'البريد الإلكتروني',
    'login.btn.admin':      'دخول',
    // s4
    'login.s4.title':       'تم بنجاح! 🎉',
    'login.s4.sub':         'مرحباً بك في VOLD MOTOR',
    'login.s4.btn':         'الذهاب للوحة التحكم',
    // photo side
    'login.photo.tagline':  'نظام إدارة مراكز العناية بالمركبات',
    'login.photo.sub':      'أدِر مركزك، كبّر عملاءك، تابع دخلك.',
    'login.stat1':          'مركز شريك',
    'login.stat2':          'تقييم أصحاب المراكز',
    'login.stat3':          'جاهزية النظام',

    // ── SIDEBAR (dashboard pages) ──
    'side.dashboard':     'لوحة التحكم',
    'side.appointments':  'الحجوزات',
    'side.customers':     'العملاء',
    'side.inventory':     'المخزون',
    'side.messages':      'الرسائل',
    'side.reports':       'التقارير',
    'side.team':          'الفريق',
    'side.settings':      'الإعدادات',
    'side.logout':        'تسجيل الخروج',
    'side.sec.main':      'الرئيسية',
    'side.sec.manage':    'الإدارة',
    'side.sec.account':   'الحساب',
  
    // ── v3 الجديدة ──
    'nav.app':'التطبيق', 'nav.about':'من نحن', 'nav.faq':'الأسئلة الشائعة', 'nav.contact':'تواصل معنا',
    'mock.wa.v':'تم إرسال التذكير ✓','mock.wa.l':'واتساب · الآن',
    'mock.dash.hi':'صباح الخير 👋','mock.dash.shop':'مغسلة النخبة','mock.dash.live':'● مباشر',
    'mock.dash.sales':'إجمالي مبيعات الشهر','mock.dash.autoconfirm':'تأكيد حجز تلقائي',
    'mock.dash.waline':'تم إرسال تفاصيل حجز "تظليل حراري" للعميل (أ ب د 4821) بنجاح.',
    'mock.dash.occ':'معدل إشغال الحجوزات اليومي','mock.dash.cap':'إشغال',

    'mock.dash.k1':'دخل اليوم','mock.dash.k2':'حجوزات','mock.dash.k2s':'اليوم',
    'mock.dash.rev':'الإيراد · 7 أيام','mock.dash.s1':'غسيل VIP خارجي وداخلي','mock.dash.s2':'تظليل حراري 70%',

    'mock.k1':'دخل اليوم','mock.k2':'تغييرات زيت','mock.k3':'متوسط زمن الخدمة','mock.chart':'الدخل الأسبوعي',
    'mock.li1.n':'غسيل + تلميع داخلي','mock.li1.s':'جارية','mock.li2.n':'تظليل حراري كامل','mock.li2.s':'مكتملة',
    'mock.bk.v':'حجز جديد وصل','mock.bk.l':'قبل دقيقة',
    'mq.1':'غسيل وتلميع','mq.2':'تظليل حراري','mq.3':'نانو سيراميك','mq.4':'أفلام حماية PPF','mq.5':'صيانة دورية','mq.6':'إطارات وزيوت','mq.7':'تنظيف داخلي','mq.8':'تزيين وإكسسوارات',
    'val.1.b':'اشتراكك الشهري صفر','val.1.s':'لا تدفع إلا إذا ربحت',
    'val.2.b':'تبدأ من أول يوم','val.2.s':'التسجيل ياخذ دقائق وتنطلق',
    'val.3.b':'عربي بالكامل','val.3.s':'مع دعم كامل للإنجليزية',
    'val.4.b':'يعمل من المتصفح','val.4.s':'على أي جهاز، بدون تحميل',
    'feat.wa.1':'موعدك بكرة الساعة 3:30 م 🚗','feat.wa.2':'تمام، أشوفكم 👍',
    'feat.inv.1':'زيت 5W-30','feat.inv.2':'فلتر هواء',
    'price.note':         'تفاصيل العمولة الكاملة تظهر لك بشفافية عند تسجيل مركزك.',
        'app.h2':'مركزك في جيبك',
    'app.p':'تابع حجوزاتك ودخلك وسرعة عمالك من أي مكان — وأنت في بيتك. تطبيق VOLD MOTOR قادم قريباً لآيفون وأندرويد، وحتى ذلك الحين النظام يعمل بالكامل من متصفح جوالك.',
    'app.soon':'قريباً','app.soon2':'قريباً','app.soon3':'قريباً','app.soon4':'قريباً',
    'ph.k1':'دخل اليوم','ph.k2':'حجوزات','ph.li1':'غسيل VIP','ph.li2':'تظليل كامل','ph.li3':'فيلم حماية PPF','ph.cta':'+ حجز جديد',
    'foot.col1.l3':'التطبيق','foot.col1.l4':'تسجيل الدخول',
    'foot.col2.l4':'سياسة الخصوصية','foot.col3.h':'حمّل التطبيق',
    'foot.mini1':'الخصوصية','foot.mini2':'الأسئلة الشائعة','foot.mini3':'تواصل معنا',
  
    // ── v4 ──
    'ind.h2':'مهما كان مجالك، لوحتك تتشكّل عليه',
    'ind.sub':'بيانات مركزك ملكك وحدك ومعزولة بالكامل، والنظام يتشكّل حسب نشاطك — كل مجال يشوف اللي يحتاجه بالضبط.',
    'ind.t1':'مغسلة سيارات','ind.t2':'محل زيوت وفلاتر','ind.t3':'تظليل وحماية','ind.t4':'مركز صيانة',
    'ind.1.h':'لوحة المغسلة تركّز على السرعة','ind.1.p':'طابور اليوم لحظة بلحظة، الباقات الأكثر طلباً، وتذكير العملاء الدوريين تلقائياً.',
    'ind.1.c1':'⏱️ طابور الانتظار المباشر','ind.1.c2':'📦 باقات الغسيل والاشتراكات','ind.1.c3':'🔁 العملاء الدوريون','ind.1.c4':'💰 دخل كل وردية',
    'ind.2.h':'لوحة محل الزيوت تركّز على المخزون','ind.2.p':'كل نوع زيت بسعره وكميته المتبقية، تنبيه قبل النفاد، وسجل عملاء الفترة ومبيعاتها.',
    'ind.2.c1':'🛢️ أنواع الزيوت وأسعارها','ind.2.c2':'📉 الكمية المتبقية لكل صنف','ind.2.c3':'🔔 تنبيه قبل نفاد المخزون','ind.2.c4':'📊 عملاء ومبيعات الفترة',
    'ind.3.h':'لوحة التظليل تركّز على المواعيد','ind.3.p':'حجوزات بمدد دقيقة لكل سيارة، مخزون الأفلام بالأمتار، وضمانات العملاء موثّقة.',
    'ind.3.c1':'📅 مواعيد بمدد التنفيذ','ind.3.c2':'🎞️ مخزون الأفلام والدرجات','ind.3.c3':'🛡️ سجل الضمانات','ind.3.c4':'🚗 ملف كل سيارة وخدماتها',
    'ind.4.h':'لوحة الصيانة تركّز على ملف السيارة','ind.4.p':'تاريخ صيانة كامل لكل مركبة، قطع الغيار المستخدمة، وتذكير العميل بالصيانة القادمة.',
    'ind.4.c1':'📋 تاريخ صيانة كل مركبة','ind.4.c2':'⚙️ قطع الغيار والتكاليف','ind.4.c3':'⏰ تذكير الصيانة الدورية','ind.4.c4':'🧾 فواتير وتقارير مفصّلة',
    'ind.lock':'بياناتك معزولة بالكامل — لا يطّلع عليها أي مركز آخر، ولا نشاركها مع أحد.',
    'mock.greet':'مركز زيوت السرعة','mock.date':'الخميس 12 يونيو','mock.week':'7 أيام',
    'wa.online':'متصل الآن',
    'wa.m1':'مساء الخير أبو محمد 🌟 نذكّرك بموعدك بكرة الساعة 3:30 م — غسيل وتلميع داخلي. نشوفك على خير!',
    'wa.m2':'حياك الله، أبشر موجود 👍',
    'cust.visits':'عدد الزيارات','cust.spent':'إجمالي (ر.س)','cust.lastv':'قبل 3 أيام','cust.last':'آخر زيارة',
            'ph.hi':'صباح الخير 👋','ph.shop':'مركز درع الحماية','ph.today':'جدول اليوم','ph.all':'الكل',
    'ph.li1':'نانو سيراميك كامل','ph.li2':'تظليل حراري 70%','ph.li3':'فيلم حماية PPF',
  
    // ── v5 ──
    'acct.boss':'حساب المشرف','acct.boss.s':'لوحة تحكم مستقلة كاملة',
    'acct.staff':'حساب العمالة','acct.staff.s':'للإدخال وتحديث الحالة فقط',
    'mock.min':'دقيقة',
    'pipe.1':'بالانتظار','pipe.2':'جاري العمل','pipe.3':'انتهى',
    'pipe.oil1':'زيت 5W-30','pipe.oil2':'زيت + فلتر','pipe.timer':'منذ 6 دقائق','pipe.speed':'أسرع بـ 12% من أمس',
    'mock.alert':'تنبيه مخزون: فلتر زيت تويوتا — باقي 4 حبات فقط','mock.order':'اطلب الآن',
    'ind.1.r1a':'طابور الانتظار','ind.1.r1b':'يتحدّث لحظة بلحظة',
    'ind.1.r2a':'باقات الغسيل','ind.1.r2b':'الأكثر طلباً ودخلاً',
    'ind.1.r3a':'العملاء الدوريون','ind.1.r3b':'تذكير تلقائي بالعودة',
    'ind.2.r1a':'المخزون بالتفصيل','ind.2.r1b':'كل نوع بسعره وكميته المتبقية',
    'ind.2.r2a':'تنبيه قبل النفاد','ind.2.r2b':'لا تتفاجأ بصنف خالص',
    'ind.2.r3a':'مبيعات الفترة','ind.2.r3b':'كم عميل وكم دخل — برقم واضح',
    'ind.3.r1a':'مواعيد بمدد دقيقة','ind.3.r1b':'كل سيارة بوقت تنفيذها',
    'ind.3.r2a':'مخزون الأفلام','ind.3.r2b':'بالأمتار والدرجات',
    'ind.3.r3a':'سجل الضمانات','ind.3.r3b':'موثّق لكل عميل',
    'ind.4.r1a':'ملف كل مركبة','ind.4.r1b':'تاريخ صيانة كامل',
    'ind.4.r2a':'قطع الغيار','ind.4.r2b':'المستخدمة وتكاليفها',
    'ind.4.r3a':'الصيانة القادمة','ind.4.r3b':'تذكير العميل تلقائياً',
    'bk.today':'اليوم — الخميس 12 يونيو','bk.count':'8 حجوزات',
    'bk.s1':'غسيل + تلميع داخلي','bk.s2':'تغيير زيت وفلتر','bk.s3':'تظليل حراري كامل',
    'bk.st1':'جارية','bk.st2':'قادمة','bk.st3':'قادمة',
    'inv.h1':'الصنف','inv.h2':'السعر','inv.h3':'المتبقي',
    'sf.1':'بالانتظار','sf.2':'جاري العمل','sf.3':'انتهى','sf.stat':'متوسط الإنجاز: 14 دقيقة',
    'price.zero.b':'ريال شهرياً','price.zero.s':'دائماً وأبداً — مهما كبر مركزك',
    'price.pitch':'إذا ربحت، تدفع عمولة رمزية فقط. ما ربحت؟ ما تدفع شيء.',
  
    // ── v6 ──
    'ind.t5':'+ وغيرها',
    'bk.day':'يوم','bk.week':'أسبوع',
    'bk.e1':'غسيل VIP خارجي وداخلي','bk.e2':'تظليل حراري 70%','bk.e3':'حماية نانو سيراميك','bk.e6':'غسيل + تلميع داخلي',
    'bk.min':'د','bk.wa3':'تم 🌟 سيارتك جاهزة','bk.wa4':'يعطيك العافية','wa.m3':'تم 🌟 سيارتك جاهزة الحين، تقدر تمر تستلمها','wa.m4':'يعطيك العافية، خدمة ممتازة 🌹',
    'inv.sum':'142 صنف في المخزون','inv.alerts':'تنبيهان ⚠','inv.h4':'الحالة',
    'inv.ok':'متوفر','inv.ok2':'متوفر','inv.low':'منخفض',
    'cust.car':'لكزس LX570 · موديل 2023','cust.cars':'زيارة / شهر',
    'ai.h2':'نهاية كل شهر، الذكاء الاصطناعي يحلل مركزك',
    'ai.p':'كل سيارة تدخل مركزك تمر بثلاث مراحل يسجّلها عمالك بوقتها: بالانتظار، جاري العمل، انتهى. هذي البيانات ما تروح سدى — نهاية كل شهر نسحبها ونعدّ لك تقريراً تحليلياً ذكياً يقرأ أرقامك بدالك.',
    'ai.li1':'مقارنة أداء الشهر بالشهور الماضية — صعود أو نزول وليش',
    'ai.li2':'أوقات الذروة بالساعة واليوم — متى تحتاج عمالة أكثر',
    'ai.li3':'مدة الإنجاز لكل مرحلة — وين يتأخر الشغل بالضبط',
    'ai.li4':'توصيات عملية مكتوبة بلغة واضحة — مو مجرد أرقام',
    'ai.doc.t':'التقرير التحليلي الشهري','ai.doc.s':'مركز زيوت السرعة · يونيو 2026','ai.doc.b':'AI ✦',
    'ai.k1':'مقارنة بالشهر الماضي','ai.k2':'متوسط الإنجاز','ai.k3':'أوقات الذروة','ai.k4':'متوسط زمن كل مرحلة',
    'ai.min':'دقيقة','ai.s1':'بالانتظار','ai.s2':'جاري العمل',
    'ai.note':'💡 ذروة الخميس 6م تحتاج عاملاً إضافياً — الانتظار فيها أطول بـ 9 دقائق عن المعدل.',
  
    // ── v7 ──
    'bk.shop':'حساب: مغسلة النخبة','bk.scope':'يعرض خدمات نشاطه فقط',
  
    // ── v11 ──
      'bk.pm':'م',
      'inv.alert.t':'صنفان يحتاجان انتباهك','inv.alert.s':'مخزون منخفض — يُنصح بإعادة الطلب',
  },

  en: {

    /* ── ADMIN (auto) ── */
    'stat.total': 'Total Requests',
    'stat.pending': 'Pending Requests',
    'stat.approved': 'Active Centers',
    'stat.rejected': 'Rejected Requests',
    'ad.overview': 'Overview',
    'ad.joinRequests': 'Join Requests',
    'ad.platform': 'Platform',
    'ad.subscribedCenters': 'Subscribed Centers',
    'ad.platformStats': 'Platform Statistics',
    'ad.rejectedRequests': 'Rejected Requests',
    'ad.title': 'Super Admin Panel',
    'ad.refresh': 'Refresh',
    'ad.platformRevenue': 'Total Platform Revenue · This Month',
    'ad.underDev': 'Under development — coming soon',
    'ad.refreshNow': 'Refresh Now',
    'ad.viewReport': 'View Report',
    'ad.sinceLaunch': 'since launch',
    'ad.needReview': '⚠ need review',
    'ad.careCenter': 'Care Centers',
    'ad.mechShop': 'Mechanic Shops',
    'ad.tintCenter': 'Tinting Centers',
    'ad.ofTotal': 'of total requests',
    'ad.monthlyGrowth': 'Monthly Sign-up Growth',
    'ad.monthlyGrowthSub': 'New join requests this year',
    'ad.monthly': 'Monthly',
    'ad.yearly': 'Yearly',
    'ad.statusDist': 'Request Status Distribution',
    'ad.statusDistSub': 'Approval, rejection and pending ratio',
    'ad.statApproved': 'Active',
    'ad.statPending': 'Pending',
    'ad.statRejected': 'Rejected',
    'ad.allRequests': 'All Requests',
    'ad.fPending': 'Pending',
    'ad.searchPh': 'Search...',
    'ad.rejectTitle': 'Reject Request',
    'ad.rejectDesc': 'You can add a note for the applicant (optional)',
    'ad.rejectPh': 'Reason for rejection or notes...',
    'ad.rejectBtn': 'Reject Request',

    /* ── SETTINGS (auto) ── */
    's.center': 'Center',
    's.svcPricesMenu': 'Services & Prices',
    's.account': 'Account',
    's.notifications': 'Notifications',
    's.danger': 'Danger Zone',
    's.centerInfo': 'Center Information',
    's.centerDesc': 'Basic info shown on invoices and reports',
    's.centerName': 'Center Name',
    's.centerNamePh': 'e.g. VOLD MOTOR',
    's.city': 'City',
    's.cityPh': 'Riyadh',
    's.district': 'District',
    's.districtPh': 'Al Naseem',
    's.address': 'Center Address (optional)',
    's.addressPh': 'King Fahd Rd, Al Naseem',
    's.openTime': 'Opening Time',
    's.closeTime': 'Closing Time',
    's.invoiceNote': 'Note shown on invoice (optional)',
    's.invoiceNotePh': 'Thank you for your visit...',
    's.svcPrices': 'Service Prices',
    's.svcPricesDesc': 'Set the default price per service — editable at each POS transaction',
    's.savePrices': 'Save Prices',
    's.accInfo': 'Account Details',
    's.accDesc': 'Center account information',
    's.emailOrPhone': 'Email / Mobile Number',
    's.newPw': 'New Password',
    's.newPwPh': 'Leave blank to keep unchanged',
    's.confirmPw': 'Confirm Password',
    's.confirmPwPh': 'Re-enter password',
    's.updatePw': 'Update Password',
    's.notifSettings': 'Notification Settings',
    's.notifDesc': 'Control the alerts you receive',
    's.notifVisit': 'Alert on new transaction',
    's.notifVisitSub': 'Sound alert when a visit is saved in POS',
    's.notifPromo': 'Promo code expiry alert',
    's.notifPromoSub': 'Alert when a promo code is about to expire',
    's.notifDaily': 'Daily Report',
    's.notifDailySub': 'Summary of the day\'s revenue at closing',
    's.notifNewCust': 'New Customer Alert',
    's.notifNewCustSub': 'Alert when a car is registered for the first time',
    's.saveSettings': 'Save Settings',
    's.dangerTitle': '⚠️ Danger Zone',
    's.dangerDesc': 'These actions cannot be undone',
    's.delMonth': 'Clear Month\'s Data',
    's.delMonthSub': 'Delete all visits and expenses of the current month',
    's.delete': 'Clear',
    's.delAll': 'Clear All Data',
    's.delAllSub': 'Delete all visits, expenses and promo codes',
    's.deleteAll': 'Clear All',
    's.logout': 'Sign Out',
    's.logoutSub': 'Sign out of your account on this device',
    's.logoutBtn': 'Sign Out',
    's.savedOk': '✅ Saved successfully',

    /* ── TEAM (auto) ── */
    't.addEmp': 'Add Employee',
    't.totalTeam': 'Total Team',
    't.employee': 'employees',
    't.managers': 'Managers',
    't.manager': 'Manager',
    't.cashiers': 'Cashiers',
    't.cashier': 'Cashier',
    't.techs': 'Technicians',
    't.tech': 'Technician',
    't.noEmp': 'No employees yet',
    't.noEmpSub': 'Start by adding your first team member',
    't.addEmpTitle': 'Add New Employee',
    't.nameReq': 'Name *',
    't.namePh': 'Mohammed Ahmed',
    't.roleReq': 'Role *',
    't.chooseRole': 'Choose role...',
    't.cleaning': 'Cleaner',
    't.salary': 'Salary (SAR)',
    't.hireDate': 'Hire Date',
    't.active': 'Active',
    't.leave': 'On Leave',
    't.inactive': 'Inactive',
    't.notesPh': 'Any extra notes...',
    't.save': 'Save',
    't.saved': '✅ Saved',

    /* ── REPORTS (auto) ── */
    'r.exportCsv': 'Export CSV',
    'r.print': 'Print',
    'r.thisYear': 'This Year',
    'r.custom': 'Custom',
    'r.from': 'From:',
    'r.to': 'To:',
    'r.apply': 'Apply',
    'r.totalRev': 'Total Revenue',
    'r.totalExp': 'Total Expenses',
    'r.carCount': 'Car Count',
    'r.visit': 'visits',
    'r.revVsExp': 'Revenue & Expenses',
    'r.svcDist': 'Services Distribution',
    'r.mostReq': 'Most Requested',
    'r.svcRank': 'Services Ranking',
    'r.byOrders': 'by number of orders',
    'r.lastVisits': 'Recent Visits',
    'r.expDist': 'Expenses Distribution',
    'r.byCategory': 'by category',
    'r.lastExp': 'Recent Expenses',
    'r.thPlate': 'Plate',
    'r.thService': 'Service',
    'r.thNet': 'Net',
    'r.thAmount': 'Amount',
    'r.loading': 'Loading...',

    /* ── EXPENSES (auto) ── */
    'e.title': '💰 Expenses',
    'e.monthExp': 'Month\'s Expenses',
    'e.todayExp': 'Today\'s Expenses',
    'e.topItem': 'Largest Item',
    'e.itemCount': 'Items This Month',
    'e.addExp': '➕ Add Expense',
    'e.catRent': '🏠 Rent',
    'e.catElec': '⚡ Electricity',
    'e.catWater': '💧 Water',
    'e.catSalary': '👷 Salaries',
    'e.catSupplies': '🛒 Supplies',
    'e.catOther': '📦 Other',
    'e.desc': 'Description',
    'e.descPh': 'e.g. January rent',
    'e.amount': 'Amount (SAR)',
    'e.recurring': 'Recurring expense (monthly)',
    'e.save': 'Save Expense',
    'e.log': 'Expense Log',

    /* ── MESSAGES (auto) ── */
    'm.templates': 'Templates',
    'm.newMsg': 'New Message',
    'm.searchConv': 'Search conversations...',
    'm.unread': 'Unread',
    'm.sent': 'Sent',
    'm.chooseConv': 'Select a conversation',
    'm.chooseConvSub': 'Select a conversation from the list or start a new message',
    'm.waInputPh': 'Type a WhatsApp message...',
    'm.templatesTitle': 'Message Templates',
    'm.message': 'Message',
    'm.msgPh': 'Write your message here...',
    'm.orTemplate': 'Or choose a template:',
    'm.custSearchPh': 'Search by customer name or phone...',
    'm.sendWa': 'Send WhatsApp',

    /* ── INVENTORY (auto) ── */
    'i.logMovement': 'Log Movement',
    'i.newItem': 'New Item',
    'i.totalItems': 'Total Items',
    'i.thisMonth': 'this month',
    'i.invValue': 'Inventory Value',
    'i.lowStock': 'Low Stock',
    'i.needReorder': 'need reorder',
    'i.outStock': 'Out of Stock',
    'i.orderNow': 'order immediately',
    'i.alertReorder': 'Alert: 6 items need reorder',
    'i.catOil': 'Oils',
    'i.catFilter': 'Filters',
    'i.catTire': 'Tires',
    'i.catBrake': 'Brakes',
    'i.catSpark': 'Spark Plugs',
    'i.catOther': 'Other',
    'i.searchPh': 'Search by item name or SKU...',
    'i.thItem': 'Item',
    'i.thCat': 'Category',
    'i.thQty': 'Quantity',
    'i.thMin': 'Minimum',
    'i.thStock': 'Stock',
    'i.thUnitPrice': 'Unit Price',
    'i.thTotal': 'Total',
    'i.addTitle': 'Add New Item',
    'i.itemName': 'Item Name',
    'i.itemNamePh': 'e.g. Motor Oil 5W-30',
    'i.category': 'Category',
    'i.curQty': 'Current Quantity',
    'i.minAlert': 'Minimum Alert Level',
    'i.unitPriceSar': 'Unit Price (SAR)',
    'i.sku': 'SKU',
    'i.supplierPh': 'Supplier, extra details...',
    'i.saveItem': 'Save Item',
    'i.moveTitle': 'Log Stock Movement',
    'i.moveType': 'Movement Type',
    'i.addStock': 'Add to Stock',
    'i.removeStock': 'Remove from Stock',
    'i.item': 'Item',
    'i.chooseItem': 'Choose item...',
    'i.reason': 'Reason / Note',
    'i.reasonPh': 'e.g. Used in booking #124, received from supplier...',
    'i.lastMoves': 'Recent Movements',
    'i.saveMove': 'Log Movement',
    'i.totalValue': 'Total Value',
    'i.logMovementShort': '+ Log Movement',
    'i.close': 'Close',

    /* ── POS (auto) ── */
    'p.title': '🖥️ Cashier',
    'p.plate': '🚗 Plate Number',
    'p.platePh': 'Enter plate number',
    'p.phone': '📱 Mobile Number',
    'p.custName': '👤 Customer Name',
    'p.optional': '(optional)',
    'p.svcType': '🔧 Service Type',
    'p.svcTire': 'Tire Repair',
    'p.svcBattery': 'Battery Change',
    'p.svcLube': 'Lubrication',
    'p.price': '💰 Price (SAR)',
    'p.promo': '🏷️ Promo Code',
    'p.notes': '📝 Notes',
    'p.saveVisit': 'Save Visit & Issue Invoice',
    'p.todayLog': 'Today\'s Log',
    'p.noVisits': 'No visits yet today',
    'p.enterData': 'Enter visit details to preview the invoice',
    'p.printInvoice': 'Print Invoice',
    'p.visitDone': 'Visit Completed ✅',
    'p.creditAdded': '🎁 Credit added for the next visit',
    'p.firstPromo': '🏷️ First Promo Code',
    'p.valid30once': 'Valid 30 days · one-time only',
    'p.newVisit': 'New Visit',
    'p.print': '🖨️ Print',

    /* ── APPOINTMENTS (auto) ── */
    'a.viewList': 'List',
    'a.viewDay': 'Today',
    'a.viewWeek': 'Week',
    'a.newBooking': 'New Booking',
    'a.vsYesterday': 'vs yesterday',
    'a.inProgress': 'In Progress',
    'a.nowAtCenter': 'now at the center',
    'a.completedToday': 'Completed Today',
    'a.completion': 'completion',
    'a.sar': 'Saudi Riyal',
    'a.fAll': 'All',
    'a.fPending': 'Pending',
    'a.fProgress': 'In Progress',
    'a.fCancel': 'Cancelled',
    'a.plateReq': 'Plate Number *',
    'a.platePh': 'ABC 1234',
    'a.custOpt': 'Customer Name (optional)',
    'a.serviceReq': 'Service *',
    'a.chooseService': 'Choose a service...',
    'a.svcPolish': 'Polishing',
    'a.svcTire': 'Tires',
    'a.date': 'Date',
    'a.time': 'Time',
    'a.duration': 'Expected Duration',
    'a.dur30': '30 minutes',
    'a.dur60': '1 hour',
    'a.dur90': '1.5 hours',
    'a.dur120': '2 hours',
    'a.dur180': '3 hours',
    'a.expectedCost': 'Expected Cost (SAR)',
    'a.notesPh': 'Any extra details...',
    'a.saveBooking': 'Save Booking',

    /* ── CUSTOMERS (auto) ── */
    'c.back': 'Back',
    'c.newCust': 'New Customer',
    'c.totalCust': 'Total Customers',
    'c.custMonth': 'Customers This Month',
    'c.carsReg': 'Registered Cars',
    'c.thisWeek': 'this week',
    'c.vsLastMonth': 'vs last month',
    'c.avgCars': 'avg 1.6 cars/customer',
    'c.searchPh': 'Search by name, phone or plate...',
    'c.filter': 'Filter',
    'c.sort': 'Sort',
    'c.loading': 'Loading customers...',
    'c.addTitle': 'Add New Customer',
    'c.custNamePh': 'Customer name',
    'c.carData': 'Vehicle Details',
    'c.platePh': 'ABC 1234',
    'c.carPh': 'Camry, Patrol...',
    'c.notes': 'Notes',
    'c.notesPh': 'Any notes...',
    'c.cancel': 'Cancel',
    'c.saveCust': 'Save Customer',
    'c.mobile': 'Mobile',
    'c.totalVisits': 'Total Visits',
    'c.totalSpend': 'Total Spend',
    'c.whatsapp': 'Message on WhatsApp',
    'c.newBooking': '+ New Booking',
    'c.editData': 'Edit Details',

    /* ── DASHBOARD (auto) ── */
    'stat.todayRev': 'Today\'s Income',
    'stat.todayCars': 'Today\'s Cars',
    'stat.customers': 'Customers',
    'stat.monthRev': 'Month\'s Income',
    'stat.netProfit': 'Net Profit',
    'd.nav.dash': 'Dashboard',
    'd.nav.pos': 'Cashier',
    'd.nav.appt': 'Appointments',
    'd.nav.cust': 'Customers',
    'd.nav.inv': 'Inventory',
    'd.sec.comm': 'Communication',
    'd.nav.msg': 'Messages',
    'd.nav.exp': 'Expenses',
    'd.nav.rep': 'Reports',
    'd.nav.team': 'Team',
    'd.nav.set': 'Settings',
    'd.home': 'Home',
    'd.pageTitle': 'Dashboard',
    'd.newTx': 'New Transaction',
    'd.lastHour': '⚡ Last Hour Performance',
    'd.q.appt': 'Bookings',
    'd.q.exp': 'Expenses',
    'd.lastHourMini': 'Last Hour',
    'd.vsDaily': 'vs daily average',
    'd.carsLastHour': 'cars in the last hour',
    'd.techOcc': 'Technician Occupancy',
    'd.realWork': 'actual work rate today',
    'd.teamCapacity': 'of full team capacity',
    'd.todayBookings': 'Today\'s Bookings',
    'd.upcomingInprog': 'Upcoming + In Progress',
    'd.activeNow': 'active bookings now',
    'd.upcoming': 'Upcoming',
    'd.inprog': 'In Progress',
    'd.dailyIncome': '📈 Daily Income — This Month',
    'd.fromPos': 'from POS',
    'd.expensesBtn': '💰 Expenses',
    'd.peakHours': '⏰ Peak Hours — This Week',
    'd.peakSub': 'busiest hours across the week',
    'd.thisWeek': 'This Week',
    'd.dailyCars': 'Daily cars',
    'd.peakDays': 'Peak days',
    'd.viewAll': 'View All',
    'd.recentActivity': 'Recent Activity',
    'd.topServices': 'Top Services',
    'd.thisMonth': 'This Month',
    'd.newTxH': 'New Transaction',
    'd.newTxSub': 'Log a new service',
    'd.customer': 'Customer',
    'd.searchCust': 'Search by name or phone...',
    'd.newCust': 'New Customer',
    'd.fullName': 'Full Name',
    'd.phone': 'Phone Number',
    'd.svcType': 'Service Type',
    'd.svc.wash': 'Wash',
    'd.svc.tint': 'Tinting',
    'd.svc.maint': 'Maintenance',
    'd.svc.oil': 'Oil Change',
    'd.svc.detail': 'Detailing',
    'd.svc.paint': 'Paint Protection',
    'd.carType': 'Car Type',
    'd.carPh': 'Camry / Hilux...',
    'd.plate': 'Plate Number',
    'd.amount': 'Amount (SAR)',
    'd.status': 'Status',
    'd.st.pending': 'Upcoming',
    'd.st.inprog': 'In Progress',
    'd.st.done': 'Completed',
    'd.paid': 'Payment Received',
    'd.saveTx': 'Save Transaction',
    // ── NAV (index) ──
    'nav.features':       'Features',
    'nav.results':        'Results',
    'nav.pricing':        'Pricing',
    'nav.testimonials':   'Reviews',
    'nav.login':          'Sign In',
    'nav.register':       'Register Your Center Free',

    // ── HERO ──
    'hero.pill':          'Vehicle Care Center Management System',
    'hero.h1.a':          'The #1 platform for',
    'hero.h1.b':          'vehicle care centers',
    'hero.h1.c':          '',
    'hero.badge':         'Built in Saudi Arabia 🇸🇦 for vehicle care centers',
    'hero.fc1':           'Today revenue',
    'hero.fc2':           'Bookings today',
    'hero.lead':          'Whether you run a car wash, detailing, or oil-change shop — we built this system to fit you. Track every car from arrival to handover, and stay in touch with your customers at the tap of a button.',
    'hero.cta1':          'Start Free',
    'hero.cta2':          'Explore Features',
    'hero.tag':           'Cloud platform for vehicle care centers',
    'hero.note':          'No monthly fees · a small commission on completed jobs only',
    'hero.rating':        '4.9/5 rated by center owners',
    'hero.partners':      '400+ partner centers trust us',
    'hero.stat1.val':     '4,250 SAR',
    'hero.stat1.lbl':     "Today's Revenue",
    'hero.stat2.val':     '18 Jobs',
    'hero.stat2.lbl':     'Today',

    // ── TRUST ──
    'trust.1.lbl':  'Partner Centers',
    'trust.2.lbl':  'Operations Managed Monthly',
    'trust.3.lbl':  'Owner Rating',
    'trust.4.lbl':  'System Uptime',

    // ── FEATURES ──
    'feat.eyebrow':   'Features',
    'feat.h2':        'One system to run your center completely',
    'feat.sub':       'Ditch the paper logbooks and spreadsheets — everything in one organized place.',
    'feat.1.title':   'Appointment Management',
    'feat.1.desc':'A clear daily & weekly calendar for your own trade — every account is independent and shows only its services.',
    'feat.2.title':   'Customer Database',
    'feat.2.desc':    'Full record of every customer and their vehicles — search by name or plate number in seconds.',
    'feat.3.title':   'Inventory Management',
    'feat.3.desc':    'Track oils, tires and spare parts — automatic alert when stock runs low.',
    'feat.4.title':   'WhatsApp Communication',
    'feat.4.desc':    'Send reminders, confirmations and offers to customers via WhatsApp directly from the system.',
    'feat.5.title':   'Revenue Reports',
    'feat.5.desc':    'Daily, monthly and annual revenue — clearer decisions with real data from your center.',
    'feat.6.title':'Monitor your staff from home',
    'feat.6.desc':'A full supervisor account plus entry-only staff accounts — workers update each car through three stages while you track speed and progress from your phone, wherever you are.',

    // ── SPLIT 1 ──
    'split1.eyebrow': 'WhatsApp Communication',
    'split1.h3':      'Communicate with your customers directly from the system',
    'split1.p':       'Send appointment reminders, job confirmations and special offers — all from VOLD MOTOR, no separate app needed.',
    'split1.li1':     'Automatic reminder before appointment',
    'split1.li2':     'Job confirmation on completion',
    'split1.li3':     'Send offers and discounts to customers',
    'split1.li4':     'Periodic maintenance reminders',

    // ── SPLIT 2 ──
    'split2.eyebrow': 'Inventory',
    'split2.h3':      'Control your inventory with precision',
    'split2.p':       'Record every product, quantity and price — receive automatic alerts when stock falls below minimum.',
    'split2.li1':     'Oils, tires and spare parts',
    'split2.li2':     'Low stock alerts',
    'split2.li3':     'Link inventory to daily operations',

    // ── RESULTS ──
    'res.eyebrow':  'Results',
    'res.h2':       'Be the managers of your own business',
    'res.sub':      'VOLD MOTOR helps you grow your center and increase your revenue.',
    'res.1.title':  'Customer Growth',
    'res.1.desc':   'Reach new customers and encourage them to return.',
    'res.2.title':  'Appointment Adherence',
    'res.2.desc':   'Reduce no-shows and late arrivals with automatic WhatsApp reminders.',
    'res.3.title':  'Revenue Increase',
    'res.3.desc':   'Organize your queue and add upsell services at visit time.',

    // ── TESTIMONIALS ──
    'tst.eyebrow':  'Customer Reviews',
    'tst.h2':       'Center owners like you trust VOLD MOTOR',
    'tst.1.q':      'Before VOLD MOTOR I wrote everything in a notebook. Now inventory, jobs and customers are all in one place.',
    'tst.1.name':   'Abu Faisal',
    'tst.1.sub':    'Golden Touch Center · Dammam',
    'tst.2.q':      'WhatsApp reminders changed my life — customers no longer forget appointments and I have time to take new clients.',
    'tst.2.name':   'Mohammed Al-Qahtani',
    'tst.2.sub':    'Pro Care Center · Khobar',
    'tst.3.q':      'Monthly reports showed me that tinting is my highest earner — I refocused and profits grew.',
    'tst.3.name':   'Saad Al-Otaibi',
    'tst.3.sub':    'Itqan Center · Riyadh',

    // ── PRICING ──
    'price.eyebrow':      'Commission',
    'price.h2':           'Pay only when you earn',
    'price.sub':          'No monthly fees. A small commission on completed jobs only — our success is tied to yours.',
    'price.badge':        'No monthly subscription',
    'price.name':         'Commission Model',
            'price.tier1.amount': '2.5',
            'price.tier2.amount': '6.5',
        'price.li1':          'No fixed monthly fees',
    'price.li2':          'Clear contracts that protect both sides',
    'price.li3':          'Charged only on completed operations',
    'price.li4':          'All features unlocked with no limits',
    'price.cta':          'Register Your Center Free',

    // ── CTA ──
    'cta.h2':   'Your center deserves a better system',
    'cta.p':    'Join 400+ centers that organized with VOLD MOTOR. Start today — free.',
    'cta.btn1': 'Register Your Center Now',
    'cta.btn2': 'Learn More',

    // ── FOOTER ──
    'foot.desc':      'Vehicle care center management system — designed in Saudi Arabia.',
    'foot.col1.h':    'Product',
    'foot.col1.l1':   'Features',
    'foot.col1.l2':   'Pricing',
    'foot.col1.l3':   'Results',
    'foot.col2.h':    'Company',
    'foot.col2.l1':   'About us',
    'foot.col2.l2':   'Contact us',
    'foot.col2.l3':   'FAQ',
    'foot.col3.h':    'Support',
    'foot.col3.l1':   'Help Center',
    'foot.col3.l2':   'FAQ',
    'foot.col3.l3':   'Privacy Policy',
    'foot.copy':      '© 2026 VOLD MOTOR · All rights reserved',

    // ── LOGIN ──
    'login.s1.title':       'Create Account / Sign In',
    'login.merchant.h':     'Center Owner',
    'login.merchant.sub':   'Manage your bookings, customers and inventory',
    'login.admin.h':        'System Administration',
    'login.admin.sub':      'Admin dashboard and center oversight',
    'login.back':           'Back',
    'login.help':           'Help',
    'login.privacy':        'Privacy Policy',
    'login.terms':          'Terms',
    // S2 picker
    'login.picker.title':   'Center Owner?',
    'login.picker.sub':     'Choose what suits you',
    'login.reg.badge':      'No Monthly Subscriptions',
    'login.reg.title':      'Register Your Center Now',
    'login.reg.sub':        'Start in minutes — registration is free',
    'login.reg.perk1':      'Manage bookings and customers',
    'login.reg.perk2':      'Income and inventory reports',
    'login.reg.perk3':      'Cancel anytime',
    'login.reg.cta':        'Start Now',
    'login.or':             'or',
    'login.haveacc.h':      'I Have an Account',
    'login.haveacc.sub':    'Sign in to the system',
    // tl2
    'login.signin.title':   'Sign In',
    'login.signin.sub':     'Enter your account details',
    'login.phone.lbl':      'Mobile Number',
    'login.pass.lbl':       'Password',
    'login.forgot':         'Forgot password?',
    'login.btn.login':      'Enter System',
    'login.sw.noreg':       "Don't have an account?",
    'login.sw.reg':         'Register your center free',
    // tr2
    'login.reg.hdr.title':  'Register New Center',
    'login.reg.hdr.sub':    'No monthly subscriptions · Commission on completed orders only',
    'login.shop.lbl':       'Center Name',
    'login.ntype.lbl':      'Business Type',
    'login.ntype.wash':     'Wash',
    'login.ntype.tint':     'Tinting',
    'login.ntype.maint':    'Maintenance',
    'login.ntype.oil':      'Oil Change',
    'login.ntype.detail':   'Detailing',
    'login.ntype.ppf':      'Paint Protection',
    'login.name.lbl':       'Full Name',
    'login.btn.reg':        'Create Center Account',
    'login.sw.haveacc':     'Already have an account?',
    'login.sw.dologin':     'Sign In',
    // s3
    'login.s3.title':       'Admin Panel',
    'login.s3.sub':         'Restricted to system administrators',
    'login.email.lbl':      'Email Address',
    'login.btn.admin':      'Sign In',
    // s4
    'login.s4.title':       'Success! 🎉',
    'login.s4.sub':         'Welcome to VOLD MOTOR',
    'login.s4.btn':         'Go to Dashboard',
    // photo side
    'login.photo.tagline':  'Vehicle Care Center Management System',
    'login.photo.sub':      'Manage your center, grow customers, track income.',
    'login.stat1':          'Partner Centers',
    'login.stat2':          'Owner Rating',
    'login.stat3':          'System Uptime',

    // ── SIDEBAR ──
    'side.dashboard':     'Dashboard',
    'side.appointments':  'Appointments',
    'side.customers':     'Customers',
    'side.inventory':     'Inventory',
    'side.messages':      'Messages',
    'side.reports':       'Reports',
    'side.team':          'Team',
    'side.settings':      'Settings',
    'side.logout':        'Sign Out',
    'side.sec.main':      'Main',
    'side.sec.manage':    'Management',
    'side.sec.account':   'Account',

    // ── v3 new ──
    'nav.app':'App', 'nav.about':'About', 'nav.faq':'FAQ', 'nav.contact':'Contact',
    'mock.wa.v':'Reminder sent ✓','mock.wa.l':'WhatsApp · now',
    'mock.dash.hi':'Good morning 👋','mock.dash.shop':'Elite Car Wash','mock.dash.live':'● Live',
    'mock.dash.sales':'Total monthly sales','mock.dash.autoconfirm':'Auto booking confirmation',
    'mock.dash.waline':'Booking details for "heat tint" sent to customer (ABD 4821) successfully.',
    'mock.dash.occ':'Daily booking occupancy','mock.dash.cap':'capacity',

    'mock.dash.k1':'Today revenue','mock.dash.k2':'Bookings','mock.dash.k2s':'today',
    'mock.dash.rev':'Revenue · 7 days','mock.dash.s1':'VIP exterior & interior wash','mock.dash.s2':'70% heat tint',

    'mock.k1':'Today revenue','mock.k2':'Oil changes','mock.k3':'Avg. service time','mock.chart':'Weekly revenue',
    'mock.li1.n':'Wash + interior polish','mock.li1.s':'Active','mock.li2.n':'Full heat tint','mock.li2.s':'Done',
    'mock.bk.v':'New booking received','mock.bk.l':'1 min ago',
    'mq.1':'Wash & polish','mq.2':'Heat tinting','mq.3':'Nano ceramic','mq.4':'PPF protection','mq.5':'Maintenance','mq.6':'Tires & oils','mq.7':'Interior detailing','mq.8':'Accessories',
    'val.1.b':'Zero monthly fees','val.1.s':'You pay only when you earn',
    'val.2.b':'Start day one','val.2.s':'Signup takes minutes',
    'val.3.b':'Arabic-first','val.3.s':'With full English support',
    'val.4.b':'Runs in the browser','val.4.s':'Any device, no installs',
    'feat.wa.1':'Your appointment is tomorrow 3:30 PM 🚗','feat.wa.2':'Great, see you 👍',
    'feat.inv.1':'Oil 5W-30','feat.inv.2':'Air filter',
    'price.note':         'Full commission details are shown transparently when you register.',
        'app.h2':'Your shop in your pocket',
    'app.p':'Track bookings, revenue, and staff speed from anywhere — even from home. The VOLD MOTOR app is coming soon to iPhone and Android; until then, everything works from your mobile browser.',
    'app.soon':'Soon','app.soon2':'Soon','app.soon3':'Soon','app.soon4':'Soon',
    'ph.k1':'Today revenue','ph.k2':'Bookings','ph.li1':'VIP Wash','ph.li2':'Full tint','ph.li3':'PPF protection film','ph.cta':'+ New booking',
    'foot.col1.l3':'Mobile app','foot.col1.l4':'Log in',
    'foot.col2.l4':'Privacy policy','foot.col3.h':'Get the app',
    'foot.mini1':'Privacy','foot.mini2':'FAQ','foot.mini3':'Contact',

    // ── v4 ──
    'ind.h2':'Whatever your trade, your dashboard adapts to it',
    'ind.sub':'You only see what your trade needs — and your data is fully isolated, yours alone.',
    'ind.t1':'Car wash','ind.t2':'Oil & filters shop','ind.t3':'Tint & protection','ind.t4':'Service center',
    'ind.1.h':'The car-wash dashboard is built for speed','ind.1.p':'Live queue, best-selling packages, and automatic reminders for regulars.',
    'ind.1.c1':'⏱️ Live waiting queue','ind.1.c2':'📦 Wash packages & subscriptions','ind.1.c3':'🔁 Returning customers','ind.1.c4':'💰 Revenue per shift',
    'ind.2.h':'The oil-shop dashboard is built for inventory','ind.2.p':'Every oil type with its price and remaining stock, low-stock alerts, plus customer and sales reports.',
    'ind.2.c1':'🛢️ Oil types & prices','ind.2.c2':'📉 Remaining stock per item','ind.2.c3':'🔔 Low-stock alerts','ind.2.c4':'📊 Customers & period sales',
    'ind.3.h':'The tinting dashboard is built for appointments','ind.3.p':'Bookings with precise durations, film stock by the meter, and documented warranties.',
    'ind.3.c1':'📅 Timed appointments','ind.3.c2':'🎞️ Film stock & grades','ind.3.c3':'🛡️ Warranty records','ind.3.c4':'🚗 Per-vehicle profile',
    'ind.4.h':'The service dashboard is built around the vehicle file','ind.4.p':'Full maintenance history per vehicle, parts used, and next-service reminders.',
    'ind.4.c1':'📋 Maintenance history','ind.4.c2':'⚙️ Parts & costs','ind.4.c3':'⏰ Service reminders','ind.4.c4':'🧾 Detailed invoices & reports',
    'ind.lock':'Your data is fully isolated — no other center can see it, and we never share it.',
    'mock.greet':'Speed Oils Center','mock.date':'Thursday, June 12','mock.week':'7 days',
    'wa.online':'online',
    'wa.m1':'Good evening Abu Mohammed 🌟 A reminder of your appointment tomorrow at 3:30 PM — wash & interior polish. See you!',
    'wa.m2':'Thanks, I will be there 👍',
    'cust.visits':'Total visits','cust.spent':'Total (SAR)','cust.lastv':'3 days ago','cust.last':'Last visit',
            'ph.hi':'Good morning 👋','ph.shop':'Shield Pro Center','ph.today':"Today's schedule",'ph.all':'All',
    'ph.li1':'Full nano ceramic','ph.li2':'70% heat tint','ph.li3':'PPF protection film',

    // ── v5 ──
    'acct.boss':'Supervisor account','acct.boss.s':'Full independent dashboard',
    'acct.staff':'Staff account','acct.staff.s':'Entry & status updates only',
    'mock.min':'min',
    'pipe.1':'Waiting','pipe.2':'In progress','pipe.3':'Done',
    'pipe.oil1':'Oil 5W-30','pipe.oil2':'Oil + filter','pipe.timer':'6 min ago','pipe.speed':'12% faster than yesterday',
    'mock.alert':'Stock alert: Toyota oil filter — only 4 left','mock.order':'Order now',
    'ind.1.r1a':'Waiting queue','ind.1.r1b':'Updates in real time',
    'ind.1.r2a':'Wash packages','ind.1.r2b':'Best sellers & top earners',
    'ind.1.r3a':'Returning customers','ind.1.r3b':'Automatic comeback reminders',
    'ind.2.r1a':'Detailed inventory','ind.2.r1b':'Every item: price & stock left',
    'ind.2.r2a':'Low-stock alerts','ind.2.r2b':'Never run out by surprise',
    'ind.2.r3a':'Period sales','ind.2.r3b':'Customers & revenue, one clear number',
    'ind.3.r1a':'Timed appointments','ind.3.r1b':'Each car with its duration',
    'ind.3.r2a':'Film inventory','ind.3.r2b':'By the meter & grade',
    'ind.3.r3a':'Warranty records','ind.3.r3b':'Documented per customer',
    'ind.4.r1a':'Vehicle file','ind.4.r1b':'Full maintenance history',
    'ind.4.r2a':'Spare parts','ind.4.r2b':'Used parts & costs',
    'ind.4.r3a':'Next service','ind.4.r3b':'Automatic customer reminder',
    'bk.today':'Today — Thursday, June 12','bk.count':'8 bookings',
    'bk.s1':'Wash + interior polish','bk.s2':'Oil & filter change','bk.s3':'Full heat tint',
    'bk.st1':'Active','bk.st2':'Upcoming','bk.st3':'Upcoming',
    'inv.h1':'Item','inv.h2':'Price','inv.h3':'Left',
    'sf.1':'Waiting','sf.2':'In progress','sf.3':'Done','sf.stat':'Avg. completion: 14 min',
    'price.zero.b':'SAR per month','price.zero.s':'Always — no matter how big you grow',
    'price.pitch':'When you earn, you pay a small commission. No earnings? You pay nothing.',

    // ── v6 ──
    'ind.t5':'+ and more',
    'bk.day':'Day','bk.week':'Week',
    'bk.e1':'VIP exterior & interior wash','bk.e2':'70% heat tint','bk.e3':'Nano ceramic coating','bk.e6':'Wash + interior polish',
    'bk.min':'min','wa.m3':'Done 🌟 Your car is ready, drop by to pick it up','wa.m4':'Thank you, excellent service 🌹',
    'inv.sum':'142 items in stock','inv.alerts':'2 alerts ⚠','inv.h4':'Status',
    'inv.ok':'In stock','inv.ok2':'In stock','inv.low':'Low',
    'cust.car':'Lexus LX570 · 2023 model','cust.cars':'Visits / month',
    'ai.h2':'At the end of every month, AI analyzes your shop',
    'ai.p':'Every car passes through three timed stages logged by your staff: waiting, in progress, done. That data never goes to waste — each month we pull it and build a smart analytical report that reads your numbers for you.',
    'ai.li1':'Month-over-month comparison — up or down, and why',
    'ai.li2':'Peak hours by time and day — when you need more hands',
    'ai.li3':'Completion time per stage — exactly where work slows down',
    'ai.li4':'Practical recommendations in plain language — not just numbers',
    'ai.doc.t':'Monthly Analytical Report','ai.doc.s':'Speed Oils Center · June 2026','ai.doc.b':'AI ✦',
    'ai.k1':'vs. last month','ai.k2':'Avg. completion','ai.k3':'Peak hours','ai.k4':'Avg. time per stage',
    'ai.min':'min','ai.s1':'Waiting','ai.s2':'In progress',
    'ai.note':'💡 Thursday 6 PM peak needs one extra worker — waiting runs 9 minutes above average.',

    // ── v7 ──
    'bk.shop':'Account: Elite Car Wash','bk.scope':'Shows its own services only',

    // ── v11 ──
    'bk.pm':'PM',
    'inv.alert.t':'Two items need your attention','inv.alert.s':'Low stock — reorder recommended',

    // ── dashboard / admin keys ──
    'nav.features': 'Features',
    'nav.results': 'Results',
    'nav.pricing': 'Pricing',
    'nav.testimonials': 'Testimonials',
    'nav.login': 'Sign In',
    'nav.register': 'Register Your Center',
    'hero.pill': 'Vehicle Service Center Management System',
    'hero.h1.a': 'The #1 Platform for Managing',
    'hero.h1.b': 'Vehicle Service Centers',
    'hero.h1.c': '',
    'hero.cta1': 'Register Your Center Free',
    'hero.cta2': 'Explore Features',
    'hero.note': 'No monthly subscription · Small commission on completed operations only',
    'side.dash': 'Dashboard',
    'side.cashier': 'Cashier',
    'side.appts': 'Appointments',
    'side.customers': 'Customers',
    'side.inventory': 'Inventory',
    'side.messages': 'Messages',
    'side.expenses': 'Expenses',
    'side.reports': 'Reports',
    'side.team': 'Team',
    'side.settings': 'Settings',
    'side.sec.manage': 'Management',
    'stat.income.today': "Today's Revenue",
    'stat.bookings.active': 'Active Bookings',
    'stat.tech.rate': 'Technician Rate',
    'stat.last.hour': 'Last Hour',
    'stage.waiting': 'Waiting',
    'stage.working': 'In Progress',
    'stage.done': 'Completed',
    'admin.pending': 'Pending Requests',
    'admin.approved': 'Active Shops',
    'admin.rejected': 'Rejected',
    'admin.total': 'Total Applications',
    'login.title': 'Sign In',
    'login.identifier': 'Email or Phone',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.register': 'Register Your Center',
    'register.title': 'Join VOLD MOTOR',
    'register.owner': "Owner's Name",
    'register.shop': 'Shop Name',
    'register.phone': 'Phone Number',
    'register.email': 'Email Address',
    'register.location': 'Region / City',
    'register.services': 'Services Offered',
    'register.submit': 'Submit Application'
  }
};

// ── currentLang helper (for backwards compat) ─────────────────────────────────
let currentLang = localStorage.getItem('vm_lang') || 'ar';
